=== biggis-project/biggis-project.github.io/data/papers.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "List of papers",
  "type": "array",
  "items": {
    "title": "Paper",
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "date": {
        "description": "Date of the press release formatted as YYYY/MM",
        "type": "string",
        "pattern": "^[0-9]{4}/[0-9]{2}$"
      },
      "title": {
        "type": "string"
      },
      "doi": {
        "type": "string",
        "pattern": "[0-9./]"
      },
      "pdf": {
        "type": "string",
        "pattern": "^https?://"
      },
      "authors": {
        "description": "Author or a list of authors. Each formatted as: `J. Doe`",
        "type": [
          "array",
          "string"
        ],
        "minItems": 1,
        "uniqueItems": true,
        "pattern": "^[A-Z][a-z]?\\. [A-Z]"
      },
      "event": {
        "title": "",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "title": {
            "type": "string"
          },
          "place": {
            "type": "string"
          },
          "when": {
            "type": "string",
            "description": "Date or date interval of the press release formatted as `DD.MM.YYYY` or `DD.MM.YYYY - DD.MM.YYYY` or `YYYY/MM`",
            "pattern": "^[0-9]{2}\\.[0-9]{2}\\.[0-9]{4}( - [0-9]{2}\\.[0-9]{2}\\.[0-9]{4})?$|^[0-9]{4}/[0-9]{2}$"
          },
          "url": {
            "type": "string",
            "pattern": "^https?://"
          },
          "info": {
            "type": "string"
          }
        },
        "required": [
          "title",
          "url",
          "when"
        ]
      }
    },
    "required": [
      "date",
      "authors",
      "title",
      "event"
    ]
  }
}

=== biggis-project/biggis-project.github.io/data/presentations.json
[
  {
    "date": "2017/10",
    "authors": [
      "Julian Bruns",
      "Matthias Frank",
      "Viliam Simko",
      "Jens Nimis",
      "Thomas Setzer",
      "Patrick Wiener"
    ],
    "pdf": "https://indico.scc.kit.edu/indico/event/303/session/52/contribution/23/material/slides/0.pptx",
    "title": "BigGIS - Stream Enrichment With Temperature Data",
    "event": {
      "title": "2nd BMBF Big Data All Hands Meeting and 2nd Smart Data Innovation Conference",
      "when": "11.10.2017 - 12.10.2017",
      "place": "Karlsruhe",
      "url": "https://indico.scc.kit.edu/indico/event/303/overview"
    }
  },
  {
    "date": "2017/10",
    "authors": [
      "Bodo Bernsdorf",
      "Julian Bruns",
      "Katharina Glock"
    ],
    "pdf": "https://indico.scc.kit.edu/indico/event/303/session/52/contribution/24/material/slides/0.pdf",
    "title": "BigGIS - Einsatz von Flugrobotern zur Entscheidungsunterstützung bei Bränden",
    "event": {
      "title": "2nd BMBF Big Data All Hands Meeting and 2nd Smart Data Innovation Conference",
      "when": "11.10.2017 - 12.10.2017",
      "place": "Karlsruhe",
      "url": "https://indico.scc.kit.edu/indico/event/303/overview"
    }
  },
  {
    "date": "2017/09",
    "authors": [
      "Julian Bruns",
      "Daniel Seebacher",
      "Manuel Stein"
    ],
    "title": "Pedicting Habitable Zones of Invasive Species based on Temperature",
    "event": {
      "title": "OR 2017",
      "when": "6-8.09.2017",
      "place": "Berlin",
      "url": "http://or2017.de/"
    }
  },
  {
    "date": "2017/09",
    "authors": [
      "Katharina Glock",
      "Anne Meyer",
      "Guido Tack"
    ],
    "title": "Extensions to the Correlated Orienteering Problem for Emergency Surveillance",
    "event": {
      "title": "OR 2017",
      "when": "6-8.09.2017",
      "place": "Berlin",
      "url": "http://or2017.de/"
    }
  },
  {
    "date": "2017",
    "authors": [
      "Katharina Glock",
      "Anne Meyer",
      "Guido Tack"
    ],
    "pdf": "https://verolog2017.sciencesconf.org/141758/document",
    "title": "Correlated Orienteering for Planning Emergency Surveillance Flights of Unmanned Aerial Vehicles",
    "event": {
      "title": "VeRoLog 2017 - Annual Workshop of the EURO working group on Vehicle Routing and Logistics optimization",
      "place": "Amsterdam",
      "when": "10-12.07.2017",
      "url": "https://verolog2017.sciencesconf.org/"
    }
  },
  {
    "date": "2016/12",
    "authors": [
      "Daniel Seebacher",
      "Manuel Stein",
      "Daniel Keim"
    ],
    "pdf": "https://drive.google.com/open?id=135HdNLVynRfPHUZdRnpd2KVN7xPKCLh4",
    "title": "Visuelle Analyse von räumlich-zeitlichen Eventvorhersagen: Untersuchung der Ausbreitungsdynamik von invasiven Arten",
    "event": {
      "title": "6. Treffen der AG Kirschessigfliege",
      "place": "Bad Kreuznach",
      "when": "05.12.2017",
      "url": "http://www.zepp.info/termine-a-news/219-6-arbeitstreffen-der-ag-kirschessigfliege"
    }
  },
  {
    "date": "2016/09",
    "authors": [
      "Julian Bruns",
      "Boris Amberg",
      "Thomas Setzer"
    ],
    "title": "Forecasting local temperatures in urban context",
    "event": {
      "title": "OR2016 – Annual International Conference of the German Operations Research Society",
      "place": "Hamburg",
      "when": "01.09.2016",
      "url": "http://or2016.de/"
    }
  },
  {
    "date": "2016/06",
    "authors": "Matthias Frank",
    "title": "Integrating Big Spatio-Temporal Data Using Collaborative Semantic Data Management",
    "pdf": "https://link.springer.com/chapter/10.1007/978-3-319-38791-8_38",
    "event": {
      "title": "International Conference on Web Engineering (ICWE2016)",
      "place": "Lugano (CH)",
      "when": "08.06.2016",
      "url": "http://icwe2016.inf.usi.ch/"
    }
  },
  {
    "date": "2016/06",
    "authors": [
      "Andreas Abecker",
      "Torsten Brauer",
      "Johannes Kutterer",
      "Karsten Schnitter",
      "Jens Nimis",
      "Patrick Wiener"
    ],
    "title": "Überlegungen zu einer Spatial Big Data Architektur im BigGIS Projekt",
    "pdf": "https://amazonas.fzi.de/smw/sites/fzi.de.biggis/images/2/29/AK_UIS-2016_Andreas_Abecker_BigGIS_handout.pdf",
    "event": {
      "title": "23. Workshop des Arbeitskreises Umweltinformationssysteme in der Gesellschaft für Informatik (GI)",
      "url": "http://ak-uis.de/",
      "when": "03.06.2016",
      "place": "Leipzig"
    }
  },
  {
    "date": "2016/06",
    "authors": [
      "Thomas Setzer",
      "Julian Bruns"
    ],
    "title": "BigGis - Prescriptive geographical information systems (GIS) based on big data analytics infrastructures",
    "event": {
      "title": "1. Big Data All-Hands-Meeting",
      "when": "02.06.2016",
      "place": "Dresden"
    }
  },
  {
    "date": "2016/06",
    "authors": "Julian Bruns",
    "title": "BigGIS – Considering uncertainty and heterogeneity in geo-spatial Big Data",
    "event": {
      "title": "1. Big Data All-Hands-Meeting",
      "when": "02.06.2016 - 03.06.2016",
      "place": "Dresden"
    }
  },
  {
    "date": "2016/05",
    "authors": [
      "Matthias Frank",
      "Stefan Zander"
    ],
    "title": "Smart Web Services for Big Spatio-Temporal Data in Geographical Information Systems",
    "pdf": "http://ceur-ws.org/Vol-1629/paper3.pdf",
    "event": {
      "title": "Services and Applications over Linked APIs and Data (SALAD 2016)",
      "place": "Kreta (GR)",
      "when": "29.05.2016",
      "url": "http://salad2016.linked.services/menu/index.html"
    }
  },
  {
    "date": "2016/05",
    "authors": [
      "Andreas Abecker",
      "Torsten Brauer",
      "Johannes Kutterer",
      "Jens Nimis",
      "Patrick Wiener"
    ],
    "title": "Toward An Architecture for Processing Spatial Big Data",
    "pdf": "https://amazonas.fzi.de/smw/sites/fzi.de.biggis/images/5/5e/GWF-2016_Andreas_Abecker_v2.pdf",
    "event": {
      "title": "Geospatial World Forum (GWF 2016)",
      "url": "http://geospatialworldforum.org/",
      "when": "25.05.2016",
      "place": "Rotterdam (NL)"
    }
  },
  {
    "date": "2016/05",
    "authors": "Andreas Abecker",
    "title": "Smart Geodata: Anwendungsfelder und Herausforderungen",
    "link": "http://rg-wuerzburg.gi.de/veranstaltungen.html",
    "event": {
      "title": "Regionalgruppe Würzburg der Gesellschaft für Informatik (GI)",
      "url": "http://rg-wuerzburg.gi.de/veranstaltungen.html",
      "when": "03.05.2016",
      "place": "Würzburg"
    }
  },
  {
    "date": "2016/02",
    "authors": "Bodo Bernsdorf",
    "title": "Big Data and Data Mining in Fire Services - a first perspective",
    "pdf": "https://amazonas.fzi.de/smw/sites/fzi.de.biggis/images/5/5f/20160202_BigGIS_for_Fire_Services.pdf",
    "event": {
      "title": "GI-Forum des Institut für Geoinformatik an der Universtität Münster (IfGI)",
      "url": "http://www.uni-muenster.de/Geoinformatics/GI-Forum/index.shtml",
      "when": "02.02.2016",
      "place": "Münster"
    }
  },
  {
    "date": "2015/11",
    "authors": "Bodo Bernsdorf",
    "title": "BigGIS - Wie Copernicus und Flugroboter den Feuerwehreinsatz verändern",
    "pdf": "https://amazonas.fzi.de/smw/sites/fzi.de.biggis/images/4/4e/20151105_BigGIS_und_Copernicus_f%C3%BCr_MRM.pdf",
    "event": {
      "title": "Workshop: Copernicus - (K)ein Thema für Land und Kommune? beim Nationalen Forum für Fernerkundung und Copernicus",
      "url": "http://www.d-copernicus.de/sites/default/files/dokumente/Forum_2015/Bernsdorf_EFTAS.pdf",
      "when": "05.11.2015",
      "place": "BMVI, Berlin"
    }
  },
  {
    "date": "2015/11",
    "authors": "Matthias Frank",
    "title": "Dynamic integration of geo temporal data due to semantically described heterogeneous sources within the BigGIS project",
    "pdf": "https://amazonas.fzi.de/smw/sites/fzi.de.biggis/images/f/f1/Dynamic_integration_of_geo_temporal_data_due_to_semantically_described_heterogeneous_sources_within_the_BigGIS_project.pdf",
    "event": {
      "title": "Fast Data SIG",
      "url": "https://km.aifb.kit.edu/intern/LIOWiki/index.php/Big/Fast_Data-SIG Big/Fast_Data-SIG",
      "when": "16.11.2015",
      "place": "Karlsruhe"
    }
  },
  {
    "date": "2015/09",
    "authors": "Andreas Abecker",
    "title": "Smart Geodata - Applications and Challenges",
    "pdf": "https://amazonas.fzi.de/smw/sites/fzi.de.biggis/images/b/bb/Aab-INFORMATIK-2015.pdf",
    "event": {
      "title": "Workshop: Big Data, Smart Data and Semantic Technologies (INFORMATIK-2015)",
      "when": "29.09.2015",
      "place": "Cottbus"
    }
  },
  {
    "date": "2015/09",
    "authors": "Wassilios Kazakos",
    "title": "Spatial Big Data - Herausforderungen und Chancen",
    "pdf": "https://amazonas.fzi.de/smw/sites/fzi.de.biggis/images/5/5b/Wk-INTERGEO-2015.pdf",
    "event": {
      "title": "Fachkongress der INTERGEO 2015",
      "url": "http://www.intergeo.de/",
      "when": "15.09.2015 - 17.09.2015",
      "place": "Messe Stuttgart"
    }
  },
  {
    "date": "2015/07",
    "authors": "Viliam Simko",
    "title": "BigGIS Project - ICMSEM'15 Keynote",
    "pdf": "https://amazonas.fzi.de/smw/sites/fzi.de.biggis/images/0/04/ICMSEM15_BigGIS_2015-07-22.pdf",
    "event": {
      "title": "The 9th International Conference on Management Science and Engineering Management (ICMSEM'15)",
      "url": "http://www.icmsem.org/past/201501/7.html",
      "when": "21.06.2015 - 23.06.2015",
      "place": "Karlsruhe"
    }
  },
  {
    "date": "2015/05",
    "authors": "Wassilios Kazakos",
    "title": "Big Data - Chancen und Herausforderungen für die Umweltinformatik",
    "pdf": "https://amazonas.fzi.de/smw/sites/fzi.de.biggis/images/8/89/Wk-akuis-2016-big-data.pdf",
    "event": {
      "title": "Workshop: Umweltinformationssysteme (AK-UIS) des GI-Arbeitskreises „Umweltinformationssysteme“",
      "url": "http://www.ak-uis.de/",
      "when": "07.05.2015",
      "place": "Universität Kassel"
    }
  },
  {
